
#line 3 "params_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer params__create_buffer
#define yy_delete_buffer params__delete_buffer
#define yy_flex_debug params__flex_debug
#define yy_init_buffer params__init_buffer
#define yy_flush_buffer params__flush_buffer
#define yy_load_buffer_state params__load_buffer_state
#define yy_switch_to_buffer params__switch_to_buffer
#define yyin params_in
#define yyleng params_leng
#define yylex params_lex
#define yylineno params_lineno
#define yyout params_out
#define yyrestart params_restart
#define yytext params_text
#define yywrap params_wrap
#define yyalloc params_alloc
#define yyrealloc params_realloc
#define yyfree params_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE params_restart(params_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int params_leng;

extern FILE *params_in, *params_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up params_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up params_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via params_restart()), so that the user can continue scanning by
	 * just pointing params_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when params_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int params_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow params_wrap()'s to do buffer switches
 * instead of setting up a fresh params_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void params_restart (FILE *input_file  );
void params__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE params__create_buffer (FILE *file,int size  );
void params__delete_buffer (YY_BUFFER_STATE b  );
void params__flush_buffer (YY_BUFFER_STATE b  );
void params_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void params_pop_buffer_state (void );

static void params_ensure_buffer_stack (void );
static void params__load_buffer_state (void );
static void params__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER params__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE params__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE params__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE params__scan_bytes (yyconst char *bytes,int len  );

void *params_alloc (yy_size_t  );
void *params_realloc (void *,yy_size_t  );
void params_free (void *  );

#define yy_new_buffer params__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        params_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            params__create_buffer(params_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        params_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            params__create_buffer(params_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

typedef unsigned char YY_CHAR;

FILE *params_in = (FILE *) 0, *params_out = (FILE *) 0;

typedef int yy_state_type;

extern int params_lineno;

int params_lineno = 1;

extern char *params_text;
#define yytext_ptr params_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up params_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	params_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 17
#define YY_END_OF_BUFFER 18
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[244] =
    {   0,
        0,    0,    0,    0,   18,   17,   11,   14,   17,   15,
       17,   12,   17,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   11,    0,   13,   15,    0,    0,   16,
        0,    0,    0,    0,    0,    0,    0,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       15,    0,    0,   16,    0,    0,    0,    4,    0,    0,
        0,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   15,    0,    0,    0,   16,    0,    0,    0,
        0,    0,    0,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,   15,    0,    0,   16,    0,    0,
        0,    2,    0,    0,    0,    0,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    0,    0,
        0,   16,    0,    0,    0,    0,    0,    0,    0,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        0,    0,   16,    3,    0,    0,    0,    8,    5,    0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        0,    0,    0,    0,    0,    7,   10,    1,    1,    1,
        1,    1,    1,    1,    0,    0,    9,    0,    1,    1,
        1,    1,    0,    0,    0,    6,    1,    1,    1,    1,

        0,    0,    1,    1,    0,    0,    0,    1,    1,    1,
        0,    0,    1,    1,    0,    0,    0,    1,    1,    1,
        0,   16,    1,    1,    0,   16,    0,    1,    1,    1,
       16,    0,    1,    1,   16,    0,    1,    1,    0,    1,
        0,    1,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    6,    7,    1,
        1,    1,    1,    1,    8,    9,    9,    9,    9,    9,
        1,    1,   10,    1,    1,    1,    1,   11,    1,    1,
        1,    1,    1,    1,   12,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   13,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,    1,    1,    1,   23,   24,
        1,   25,    1,   26,   27,   28,   12,   29,    1,    1,
        1,    1,   30,    1,   31,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[32] =
    {   0,
        1,    2,    2,    1,    3,    4,    2,    3,    3,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[286] =
    {   0,
        0,    0,   31,    0,  524,  760,  521,  760,  512,   58,
      508,  760,   59,  507,  488,  495,  473,   60,  484,  476,
        0,   65,   76,  491,   66,  489,  469,  471,  457,   68,
      468,  460,    0,  477,  475,  760,   64,  464,  463,  760,
       69,  440,  444,  446,  449,  441,  434,    0,   94,   97,
      112,  448,    0,   72,  424,  426,  422,  425,  424,  417,
       73,  428,  427,    0,   81,  407,  406,  760,  410,  409,
      406,  127,  413,  142,  157,   93,  392,  391,    0,  395,
      394,  391,   94,  397,  389,  388,  387,  374,  363,  363,
       83,  352,  355,   98,  371,  172,  187,  202,  356,  347,

      348,   97,  337,  340,  357,  353,  352,  344,    0,  322,
      329,  760,  111,  329,  326,  325,  330,  217,  232,  247,
        0,  307,  314,    0,  126,  314,  311,  302,  313,  312,
      311,  308,  286,  291,  278,  281,  286,  271,  270,  284,
      262,  277,  292,  262,  274,  261,  262,  267,  247,  246,
      267,  266,  263,  760,  252,  246,  230,  760,  760,  237,
      307,  322,  251,    0,  238,  239,  216,    0,    0,  223,
      237,  236,  233,  212,  206,  760,  760,  222,  337,  352,
      209,  201,    0,    0,  217,  209,  760,  187,  367,  382,
        0,  186,  206,  203,  194,  760,  193,  397,  412,    0,

      192,  191,  427,  442,  188,  187,  179,  178,  457,  472,
      177,  176,  487,  502,  173,  172,  164,  163,  517,  532,
      162,  161,  547,  562,  158,  157,  149,  148,  577,  592,
      147,  143,  607,  622,  133,  132,  128,  637,  127,  652,
      117,  103,  760,  671,  673,  677,  681,  683,  685,  687,
      689,   71,  691,  693,  695,  697,  699,  701,  703,  705,
      707,  709,  711,  713,  715,  717,  719,  721,  723,  725,
      727,  729,  731,  733,  735,  737,  739,  741,  743,  745,
      747,  749,  751,  753,  755
    } ;

static yyconst flex_int16_t yy_def[286] =
    {   0,
      243,    1,  243,    3,  243,  243,  243,  243,  244,  245,
      243,  243,  245,  245,  243,  243,  243,  245,  243,  243,
      246,  247,  246,  246,   23,   23,  246,  246,  246,   23,
      246,  246,  246,  243,  244,  243,  248,  249,  248,  243,
      248,  243,  243,  243,  243,  243,  243,  246,  247,   23,
       23,   50,  246,   50,  246,  246,  246,  246,  246,  246,
      250,  250,  251,  252,  250,  243,  243,  243,  243,  243,
      243,   50,   72,   72,  246,   72,  246,  246,  246,  246,
      246,  246,  243,  243,  253,  254,  255,  243,  243,  243,
      243,  243,  243,  246,  246,   74,   51,   51,  246,  246,

      246,  246,  246,  246,  243,  256,  257,  258,  252,  243,
      243,  243,  243,  243,  243,  243,  246,   74,   74,   98,
       75,  246,  246,  246,  246,  246,  246,  246,  243,  259,
      260,  261,  243,  243,  243,  243,  243,  243,  243,  246,
      119,   51,   98,  246,  246,  246,  246,  246,  246,  246,
      262,  263,  243,  243,  243,  243,  243,  243,  243,  243,
      119,  119,  246,  246,  246,  246,  246,  246,  246,  246,
      243,  264,  265,  243,  243,  243,  243,  246,  162,   51,
      246,  246,  246,  246,  266,  267,  243,  243,  162,  162,
      246,  246,  243,  268,  269,  243,  246,  190,   51,  246,

      270,  271,  190,  190,  243,  272,  273,  246,  204,   51,
      274,  275,  204,  204,  243,  276,  277,  246,  214,   51,
      278,  279,  214,  214,  243,  280,  281,  246,  224,   51,
      282,  283,  224,  224,  243,  284,  246,  224,  285,  224,
      243,  246,    0,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243
    } ;

static yyconst flex_int16_t yy_nxt[792] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,    6,   13,   14,   18,   14,   14,   14,    6,
       19,   15,    6,   16,    6,    6,   20,    6,    6,   12,
       12,   21,    7,    8,   22,   23,   24,   12,   25,   26,
       27,   28,   29,   21,   25,   26,   30,   26,   26,   26,
       21,   31,   27,   21,   28,   21,   21,   32,   21,   21,
       33,   33,   37,   38,   38,   38,   35,   36,   61,   38,
       52,   35,   52,   87,   38,   41,   73,   83,   38,   45,
       50,   51,   54,   52,   52,   65,   38,   58,   76,   52,
       52,   52,   52,   52,   52,   35,   36,   95,  105,   38,

       35,   72,  117,   51,   73,   73,   88,  113,  230,  114,
       73,   73,   73,   73,   73,   73,   74,   75,   99,   74,
       74,  125,  227,  126,  135,   74,   74,   74,   74,   74,
       74,   94,  227,  230,   95,   95,  136,  227,  227,  146,
       95,   95,   95,   95,   95,   95,   96,   97,  227,   96,
       96,  147,  227,  220,   64,   96,   96,   96,   96,   96,
       96,   98,  227,  217,   98,   98,  227,  217,  210,   64,
       98,   98,   98,   98,   98,   98,  118,  217,  207,  118,
      118,  217,  207,  199,   64,  118,  118,  118,  118,  118,
      118,  119,  207,  195,  119,  119,  207,  195,  180,   64,

      119,  119,  119,  119,  119,  119,  120,  121,  195,  120,
      120,  173,  200,  196,  195,  120,  120,  120,  120,  120,
      120,  140,  173,  192,  140,  140,  191,  142,  188,  187,
      140,  140,  140,  140,  140,  140,  141,  142,   64,  141,
      141,  173,  131,  184,  183,  141,  141,  141,  141,  141,
      141,  143,  182,  181,  143,  143,  121,  177,  176,  175,
      143,  143,  143,  143,  143,  143,  161,  174,  109,  161,
      161,  173,  131,  170,  169,  161,  161,  161,  161,  161,
      161,  162,  168,  167,  162,  162,  166,  165,  164,   97,
      162,  162,  162,  162,  162,  162,  163,  160,  159,  163,

      163,  158,  157,  156,  155,  163,  163,  163,  163,  163,
      163,  178,  154,  109,  178,  178,   64,  131,   86,  150,
      178,  178,  178,  178,  178,  178,  179,  180,  149,  179,
      179,  148,  145,  144,  117,  179,  179,  179,  179,  179,
      179,  189,  139,  138,  189,  189,  137,  134,  133,  109,
      189,  189,  189,  189,  189,  189,  190,  131,   86,  190,
      190,  105,  128,  127,  124,  190,  190,  190,  190,  190,
      190,  197,  123,  122,  197,  197,   51,  116,  115,  112,
      197,  197,  197,  197,  197,  197,  198,  199,  111,  198,
      198,  110,  109,   64,   86,  198,  198,  198,  198,  198,

      198,  203,   38,  104,  203,  203,  103,  102,  101,  100,
      203,  203,  203,  203,  203,  203,  204,   95,   93,  204,
      204,   92,   91,   90,   89,  204,  204,  204,  204,  204,
      204,  208,   86,   38,  208,  208,   82,   81,   80,   79,
      208,  208,  208,  208,  208,  208,  209,  210,   78,  209,
      209,   77,   73,   71,   70,  209,  209,  209,  209,  209,
      209,  213,   69,   68,  213,  213,   67,   66,   38,   64,
      213,  213,  213,  213,  213,  213,  214,   36,   34,  214,
      214,   60,   59,   57,   56,  214,  214,  214,  214,  214,
      214,  218,   55,   52,  218,  218,   53,   47,   46,   44,

      218,  218,  218,  218,  218,  218,  219,  220,   43,  219,
      219,   42,   38,   40,   36,  219,  219,  219,  219,  219,
      219,  223,   34,  243,  223,  223,  243,  243,  243,  243,
      223,  223,  223,  223,  223,  223,  224,  243,  243,  224,
      224,  243,  243,  243,  243,  224,  224,  224,  224,  224,
      224,  228,  243,  243,  228,  228,  243,  243,  243,  243,
      228,  228,  228,  228,  228,  228,  229,  230,  243,  229,
      229,  243,  243,  243,  243,  229,  229,  229,  229,  229,
      229,  233,  243,  243,  233,  233,  243,  243,  243,  243,
      233,  233,  233,  233,  233,  233,  234,  243,  243,  234,

      234,  243,  243,  243,  243,  234,  234,  234,  234,  234,
      234,  237,  243,  243,  237,  237,  243,  243,  243,  243,
      237,  237,  237,  237,  237,  237,  238,  243,  243,  238,
      238,  243,  243,  243,  243,  238,  238,  238,  238,  238,
      238,  240,  243,  243,  240,  240,  243,  243,  243,  243,
      240,  240,  240,  240,  240,  240,  242,  243,  243,  242,
      242,  243,  243,  243,  243,  242,  242,  242,  242,  242,
      242,   35,   35,   35,   35,   39,   39,   48,  243,   48,
       48,   49,   49,   49,   49,   62,   62,   63,   63,   84,
       84,   85,   85,  106,  106,  107,  107,  108,  108,  129,

      129,  130,  130,  132,  132,  151,  151,  152,  152,  153,
      153,  171,  171,  172,  172,  185,  185,  186,  186,  193,
      193,  194,  194,  201,  201,  202,  202,  205,  205,  206,
      206,  211,  211,  212,  212,  215,  215,  216,  216,  221,
      221,  222,  222,  225,  225,  226,  226,  231,  231,  232,
      232,  235,  235,  236,  236,  239,  239,  241,  241,    5,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243

    } ;

static yyconst flex_int16_t yy_chk[792] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,   10,   10,   13,   18,   22,   22,   37,   37,
       25,   22,   30,  252,   41,   13,   54,   61,   61,   18,
       23,   23,   25,   23,   23,   41,   65,   30,   54,   23,
       23,   23,   23,   23,   23,   49,   49,   76,   83,   83,

       49,   50,   94,   94,   50,   50,   65,   91,  242,   91,
       50,   50,   50,   50,   50,   50,   51,   51,   76,   51,
       51,  102,  241,  102,  113,   51,   51,   51,   51,   51,
       51,   72,  239,  237,   72,   72,  113,  236,  235,  125,
       72,   72,   72,   72,   72,   72,   74,   74,  232,   74,
       74,  125,  231,  228,  227,   74,   74,   74,   74,   74,
       74,   75,  226,  225,   75,   75,  222,  221,  218,  217,
       75,   75,   75,   75,   75,   75,   96,  216,  215,   96,
       96,  212,  211,  208,  207,   96,   96,   96,   96,   96,
       96,   97,  206,  205,   97,   97,  202,  201,  197,  195,

       97,   97,   97,   97,   97,   97,   98,   98,  194,   98,
       98,  193,  192,  188,  186,   98,   98,   98,   98,   98,
       98,  118,  185,  182,  118,  118,  181,  178,  175,  174,
      118,  118,  118,  118,  118,  118,  119,  119,  173,  119,
      119,  172,  171,  170,  167,  119,  119,  119,  119,  119,
      119,  120,  166,  165,  120,  120,  163,  160,  157,  156,
      120,  120,  120,  120,  120,  120,  141,  155,  153,  141,
      141,  152,  151,  150,  149,  141,  141,  141,  141,  141,
      141,  142,  148,  147,  142,  142,  146,  145,  144,  140,
      142,  142,  142,  142,  142,  142,  143,  139,  138,  143,

      143,  137,  136,  135,  134,  143,  143,  143,  143,  143,
      143,  161,  133,  132,  161,  161,  131,  130,  129,  128,
      161,  161,  161,  161,  161,  161,  162,  162,  127,  162,
      162,  126,  123,  122,  117,  162,  162,  162,  162,  162,
      162,  179,  116,  115,  179,  179,  114,  111,  110,  108,
      179,  179,  179,  179,  179,  179,  180,  107,  106,  180,
      180,  105,  104,  103,  101,  180,  180,  180,  180,  180,
      180,  189,  100,   99,  189,  189,   95,   93,   92,   90,
      189,  189,  189,  189,  189,  189,  190,  190,   89,  190,
      190,   88,   87,   86,   85,  190,  190,  190,  190,  190,

      190,  198,   84,   82,  198,  198,   81,   80,   78,   77,
      198,  198,  198,  198,  198,  198,  199,   73,   71,  199,
      199,   70,   69,   67,   66,  199,  199,  199,  199,  199,
      199,  203,   63,   62,  203,  203,   60,   59,   58,   57,
      203,  203,  203,  203,  203,  203,  204,  204,   56,  204,
      204,   55,   52,   47,   46,  204,  204,  204,  204,  204,
      204,  209,   45,   44,  209,  209,   43,   42,   39,   38,
      209,  209,  209,  209,  209,  209,  210,   35,   34,  210,
      210,   32,   31,   29,   28,  210,  210,  210,  210,  210,
      210,  213,   27,   26,  213,  213,   24,   20,   19,   17,

      213,  213,  213,  213,  213,  213,  214,  214,   16,  214,
      214,   15,   14,   11,    9,  214,  214,  214,  214,  214,
      214,  219,    7,    5,  219,  219,    0,    0,    0,    0,
      219,  219,  219,  219,  219,  219,  220,    0,    0,  220,
      220,    0,    0,    0,    0,  220,  220,  220,  220,  220,
      220,  223,    0,    0,  223,  223,    0,    0,    0,    0,
      223,  223,  223,  223,  223,  223,  224,  224,    0,  224,
      224,    0,    0,    0,    0,  224,  224,  224,  224,  224,
      224,  229,    0,    0,  229,  229,    0,    0,    0,    0,
      229,  229,  229,  229,  229,  229,  230,    0,    0,  230,

      230,    0,    0,    0,    0,  230,  230,  230,  230,  230,
      230,  233,    0,    0,  233,  233,    0,    0,    0,    0,
      233,  233,  233,  233,  233,  233,  234,    0,    0,  234,
      234,    0,    0,    0,    0,  234,  234,  234,  234,  234,
      234,  238,    0,    0,  238,  238,    0,    0,    0,    0,
      238,  238,  238,  238,  238,  238,  240,    0,    0,  240,
      240,    0,    0,    0,    0,  240,  240,  240,  240,  240,
      240,  244,  244,  244,  244,  245,  245,  246,    0,  246,
      246,  247,  247,  247,  247,  248,  248,  249,  249,  250,
      250,  251,  251,  253,  253,  254,  254,  255,  255,  256,

      256,  257,  257,  258,  258,  259,  259,  260,  260,  261,
      261,  262,  262,  263,  263,  264,  264,  265,  265,  266,
      266,  267,  267,  268,  268,  269,  269,  270,  270,  271,
      271,  272,  272,  273,  273,  274,  274,  275,  275,  276,
      276,  277,  277,  278,  278,  279,  279,  280,  280,  281,
      281,  282,  282,  283,  283,  284,  284,  285,  285,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int params__flex_debug;
int params__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *params_text;
#line 1 "params_lex.l"
/*
 *
 * This file comes from the DoCoMo SEND project
 *
 * Adapted by Sébastien Barré - sebastien.barre@uclouvain.be
 *
 * Copyright © 2006, DoCoMo Communications Laboratories USA, Inc.,
 *   the DoCoMo SEND Project
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of DoCoMo Communications Laboratories USA, Inc., its
 *    parents, affiliates, subsidiaries, theDoCoMo SEND Project nor the names
 *    of the Project's contributors may be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 *  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 *  ARE DISCLAIMED. IN NO EVENT SHALL DOCOMO COMMUNICATIONS LABORATORIES USA,
 *  INC., ITS PARENTS, AFFILIATES, SUBSIDIARIES, THE PROJECT OR THE PROJECT'S
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 *  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
 */
#line 39 "params_lex.l"
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>

#include <config.h>
#include <applog.h>

#include "params_gram.h"

int params_linecnt = 1;

/* flex option to keep -Wall quiet */

#line 783 "params_lex.c"

#define INITIAL 0
#define STRING 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int params_lex_destroy (void );

int params_get_debug (void );

void params_set_debug (int debug_flag  );

YY_EXTRA_TYPE params_get_extra (void );

void params_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *params_get_in (void );

void params_set_in  (FILE * in_str  );

FILE *params_get_out (void );

void params_set_out  (FILE * out_str  );

int params_get_leng (void );

char *params_get_text (void );

int params_get_lineno (void );

void params_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int params_wrap (void );
#else
extern int params_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( params_text, params_leng, 1, params_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( params_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( params_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, params_in))==0 && ferror(params_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(params_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int params_lex (void);

#define YY_DECL int params_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after params_text and params_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 70 "params_lex.l"


#line 967 "params_lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! params_in )
			params_in = stdin;

		if ( ! params_out )
			params_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			params_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				params__create_buffer(params_in,YY_BUF_SIZE );
		}

		params__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of params_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 244 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 760 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 72 "params_lex.l"
{
	params_lval.string = strdup(params_text);
	BEGIN 0;
	return T_STRING;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 78 "params_lex.l"
{ BEGIN STRING; return T_NAMED; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 79 "params_lex.l"
{ return T_ADDR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 80 "params_lex.l"
{ BEGIN STRING; return T_USE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 81 "params_lex.l"
{ BEGIN STRING; return T_HBASET;  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 82 "params_lex.l"
{ BEGIN STRING; return T_DERFILE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "params_lex.l"
{ BEGIN STRING; return T_KEYFILE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 84 "params_lex.l"
{ return T_SEC; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 85 "params_lex.l"
{ BEGIN STRING; return T_INTERFACE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 86 "params_lex.l"
{ BEGIN STRING; return T_SIGMETH; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 88 "params_lex.l"
{ }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 89 "params_lex.l"
{ return *params_text; }
	YY_BREAK
case 13:
*yy_cp = (yy_hold_char); /* undo effects of setting up params_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up params_text again */
YY_RULE_SETUP
#line 90 "params_lex.l"
{ }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 91 "params_lex.l"
{ params_linecnt++;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 93 "params_lex.l"
{
	params_lval.num = atoi(params_text); return T_NUMBER;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 97 "params_lex.l"
{
	struct in6_addr addr;
	int i;

	i = inet_pton(AF_INET6, params_text, &addr);
	if (i < 0) {
		applog(LOG_ERR, "Error parsing address %s (line %d): %s",
		    params_text, params_linecnt, strerror(errno));
		return T_BAD_TOKEN;
	}
	params_lval.addr6 = addr;
	return T_IPV6_ADDR;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 111 "params_lex.l"
ECHO;
	YY_BREAK
#line 1157 "params_lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed params_in at a new source and called
			 * params_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = params_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( params_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * params_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of params_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					params_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			params_restart(params_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) params_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 244 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 244 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 243);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					params_restart(params_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( params_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve params_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void params_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        params_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            params__create_buffer(params_in,YY_BUF_SIZE );
	}

	params__init_buffer(YY_CURRENT_BUFFER,input_file );
	params__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void params__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		params_pop_buffer_state();
	 *		params_push_buffer_state(new_buffer);
     */
	params_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	params__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (params_wrap()) processing, but the only time this flag
	 * is looked at is after params_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void params__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	params_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE params__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) params_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in params__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) params_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in params__create_buffer()" );

	b->yy_is_our_buffer = 1;

	params__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with params__create_buffer()
 * 
 */
    void params__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		params_free((void *) b->yy_ch_buf  );

	params_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a params_restart() or at EOF.
 */
    static void params__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	params__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then params__init_buffer was _probably_
     * called from params_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void params__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		params__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void params_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	params_ensure_buffer_stack();

	/* This block is copied from params__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from params__switch_to_buffer. */
	params__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void params_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	params__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		params__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void params_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)params_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in params_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)params_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in params_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE params__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) params_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in params__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	params__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to params_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       params__scan_bytes() instead.
 */
YY_BUFFER_STATE params__scan_string (yyconst char * yystr )
{
    
	return params__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to params_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE params__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) params_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in params__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = params__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in params__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up params_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		params_text[params_leng] = (yy_hold_char); \
		(yy_c_buf_p) = params_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		params_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int params_get_lineno  (void)
{
        
    return params_lineno;
}

/** Get the input stream.
 * 
 */
FILE *params_get_in  (void)
{
        return params_in;
}

/** Get the output stream.
 * 
 */
FILE *params_get_out  (void)
{
        return params_out;
}

/** Get the length of the current token.
 * 
 */
int params_get_leng  (void)
{
        return params_leng;
}

/** Get the current token.
 * 
 */

char *params_get_text  (void)
{
        return params_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void params_set_lineno (int  line_number )
{
    
    params_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see params__switch_to_buffer
 */
void params_set_in (FILE *  in_str )
{
        params_in = in_str ;
}

void params_set_out (FILE *  out_str )
{
        params_out = out_str ;
}

int params_get_debug  (void)
{
        return params__flex_debug;
}

void params_set_debug (int  bdebug )
{
        params__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from params_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    params_in = stdin;
    params_out = stdout;
#else
    params_in = (FILE *) 0;
    params_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * params_lex_init()
     */
    return 0;
}

/* params_lex_destroy is for both reentrant and non-reentrant scanners. */
int params_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		params__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		params_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	params_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * params_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *params_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *params_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void params_free (void * ptr )
{
	free( (char *) ptr );	/* see params_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 111 "params_lex.l"
