/*
 *	HBA test program
 *
 *      This program uses the data (testH.c) from Francis Dupont implementation
 *      of HBAs, and verifies that the resulting addresses are identical
 *      to the HBA addresses generated by his implementation.
 *      Note that the datas are slightly modified to reflect the changes from
 *      the first version of the draft HBA (implemented by F. Dupont) and
 *      to draft-ietf-shim6-hba-05
 *
 *
 *	Author:
 *	Sébastien Barré		<sebastien.barre@uclouvain.be>
 *
 *	date : April 2008
 *
 *	This program is free software; you can redistribute it and/or
 *      modify it under the terms of the GNU General Public License
 *      as published by the Free Software Foundation; either version
 *      2 of the License, or (at your option) any later version.
 */

#include <config.h>
#include <sys/types.h>
#include <stdlib.h>
#include <stdio.h>
#include <cga.h>
#include <cga_keyutils.h>
#include <applog.h>
#include <utils/util.h>
#include "cga_local.h"

/*Pseudo key*/
u_int8_t pseudokey[48] = {
	0xa3, 0x68, 0x44, 0xb5, 0x30, 0xe9,
	0x21, 0x1a, 0x4b, 0x26, 0x2b, 0x16,
	0x46, 0x7c, 0xb7, 0xdf, 0xba, 0x1f,
	0x59, 0x5c, 0x01, 0x94, 0xf2, 0x75,
	0xbe, 0x5a, 0x4d, 0x38, 0x6f, 0x2c,
	0x3c, 0x23, 0x82, 0x50, 0x87, 0x73,
	0xc7, 0x86, 0x7f, 0x9b, 0x3b, 0x9e,
	0x63, 0xa0, 0x9c, 0x7b, 0xc4, 0x8f
};

u_int8_t mod_0[16] = {
	0x89, 0xa8, 0xa8, 0xb2, 0xe8, 0x58, 0xd8, 0xb8,
	0xf2, 0x63, 0x3f, 0x44, 0xd2, 0xd7, 0xc3, 0x61
};

u_int8_t mod_1[16] = {
	0x89, 0xa8, 0xa8, 0xb2, 0xe8, 0x58, 0xd8, 0xb8,
	0xf2, 0x63, 0x3f, 0x44, 0xd2, 0xd7, 0xc3, 0x62
};

u_int8_t hash2_0[14] = {
	0x8f, 0x23, 0x8e, 0xd5, 0x3a, 0xe8,
	0xb5, 0x84, 0xd7, 0x21, 0x64, 0xc5,
	0xc1, 0x60
};

u_int8_t hash2_1[14] = {
	0x00, 0x00, 0xad, 0x8a, 0x46, 0xe8,
	0x3c, 0x44, 0x94, 0xb7, 0x61, 0x1d,
	0xd0, 0x11
};

u_int8_t pfxs[3][8] = {
	{ 0xfe, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
	{ 0x20, 0x01, 0x06, 0x88, 0x1f, 0x99, 0x00, 0x01},
	{ 0x20, 0x01, 0x06, 0x60, 0x73, 0x01, 0x00, 0x01}
};
#define NPFXS sizeof(pfxs)/sizeof(uint64_t)


u_int8_t hash1_0[8] = { 0x61, 0x8e, 0x37, 0x47, 0x6d, 0xb1, 0x2e, 0x4a };

u_int8_t hash1_1[8] = { 0x79, 0x50, 0xf7, 0xff, 0x5e, 0xec, 0x0d, 0x2a };

u_int8_t hash1_2[8] = { 0xb7, 0xb0, 0xfb, 0x52, 0xb5, 0x50, 0x0a, 0xd6 };

struct in6_addr addr_0[1] = {{{{
				0xfe, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
				0x2c, 0x5f, 0x92, 0x4d, 0x0c, 0x4c, 0x82, 0x4e
			}}}};

struct in6_addr addr_1[1] = {{{{
				0x20, 0x01, 0x06, 0x88, 0x1f, 0x99, 0x00, 0x01,
				0x3c, 0xae, 0x90, 0xc0, 0xf2, 0xb6, 0xe5, 0x82
			}}}};

struct in6_addr addr_2[1] = {{{{
				0x20, 0x01, 0x06, 0x60, 0x73, 0x01, 0x00, 0x01,
				0x3c, 0xd1, 0x77, 0x73, 0x6f, 0x00, 0xf1, 0x1b
			}}}};

#define SEC 1 /*For this test the sec parameter is 1*/

char taddr_0[] = "fe80::2c5f:924d:c4c:824e";

char taddr_1[] = "2001:688:1f99:1:3cae:90c0:f2b6:e582";

char taddr_2[] = "2001:660:7301:1:3cd1:7773:6f00:f11b";

void exit_error(char* msg)
{
	fprintf(stderr,"%s\n",msg);
	exit(EXIT_FAILURE);
}

void bad_address(const char* is, const char* shouldbe)
{

		fprintf(stderr,"computed address is %s\n",is);
		fprintf(stderr,"\tit should be %s\n",shouldbe);
		exit(EXIT_FAILURE);		
}

int main(int argc,char* argv[])
{
	static cga_ctx_t *hba;
	struct hba_set* hs;

	/*Displaying logs to stderr*/

	if (applog_open(L_STDERR, "hba_test") < 0) {
		fprintf (stderr,"applog_open failed\n");
		return EXIT_FAILURE;
	}

	applog_addlevel(log_all_on); /*Enable all log levels*/

	
	if (cga_init() < 0) {
		exit_error("cga_init failed");
	}
	
	if ((hba = new_cga_ctx()) == NULL) {
		return (-1);
	}

	hba->is_hba_ctx=1;
	
	if (cga_set_sec(hba,SEC)<0) exit_error("cga_set_sec failed");
	
	/*Is the CGA modlen 16 ?*/
	if (CGA_MODLEN!=16) {
		exit_error("HBA modifier length is not defined to 16");
	}

	cga_set_modifier_start(hba, mod_0);
	
	hs=new_hbaset_pfx("hba_test",(uint64_t*)pfxs,NPFXS);
	if (hba_set_prefixes(hba, hs)<0) {
		exit_error("hba_set_prefixes failed");
	}

	/*Setting the pseudo-key*/

	if (hba_set_pseudo(hba, pseudokey, sizeof(pseudokey))<0) 
		exit_error("HBA_set_pseudo failed\n");
	/*Generate the addresses*/
	if (hba_generate(hba)<0) exit_error("hba_generate failed");
	if (memcmp(&hba->hba_data->set_addr[0],addr_0,sizeof(struct in6_addr)))
		bad_address(addrtostr(&hba->hba_data->set_addr[0]),taddr_0);
	if (memcmp(&hba->hba_data->set_addr[1],addr_1,sizeof(struct in6_addr)))
		bad_address(addrtostr(&hba->hba_data->set_addr[1]),taddr_1);
	if (memcmp(&hba->hba_data->set_addr[2],addr_2,sizeof(struct in6_addr)))
		bad_address(addrtostr(&hba->hba_data->set_addr[2]),taddr_2);
	
	
	return EXIT_SUCCESS;
}
